backend:
  name: github
  repo: ABDULAZIZJaberALSHEHRI/azo-portfolio
  branch: main

media_folder: "assets"
public_folder: "assets"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Bio Summary", name: "bio", widget: "text"}
backend:
  name: github
  repo: ABDULAZIZJaberALSHEHRI/Azo-portfolio
  branch: main
  base_url: http://145.241.111.234:3000  # <--- This is the new link
  auth_endpoint: auth
