backend:
  name: github
  repo: ABDULAZIZJaberALSHEHRI/Azo-portfolio
  branch: main
  base_url: http://145.241.111.234:3000
  auth_endpoint: auth

media_folder: "assets"
public_folder: "assets"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Full Name", name: "name", widget: "string"}
          - {label: "Job Title", name: "title", widget: "string"}
          - {label: "Bio Summary", name: "bio", widget: "text"}
          - {label: "Profile Image", name: "profile_pic", widget: "image"}
          - label: "Social Links"
            name: "social"
            widget: "object"
            fields:
              - {label: "LinkedIn URL", name: "linkedin", widget: "string"}
              - {label: "GitHub URL", name: "github", widget: "string"}

  - name: "projects"
    label: "Projects"
    folder: "assets/projects" # This creates a folder to store project data
    create: true # Allows you to add new project cards
    fields:
      - {label: "Project Title", name: "title", widget: "string"}
      - {label: "Project Logo/Image", name: "image", widget: "image"}
      - {label: "Github Link", name: "github_url", widget: "string"}
      - {label: "Live Demo Link", name: "demo_url", widget: "string", required: false}

  - name: "certificates"
    label: "Certificates"
    folder: "assets/certificates"
    create: true
    fields:
      - {label: "Certificate Name", name: "title", widget: "string"}
      - {label: "Certificate Image", name: "image", widget: "image"}
