backend:
  name: github
  repo: https://github.com/ABDULAZIZJaberALSHEHRI/Azo-portfolio
  branch: main
  base_url: http://145.241.111.234:3000
  auth_endpoint: auth

media_folder: "assets"
public_folder: "assets"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Bio Summary", name: "bio", widget: "text"}
